# Generated by Django 4.0.2 on 2023-04-18 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0002_agency_product_supplier_importshipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_export', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=1)),
                ('total_order_value', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_import', models.IntegerField(default=0)),
                ('quantity_remain', models.IntegerField(blank=True, default=0, null=True)),
                ('import_cost', models.IntegerField(default=1)),
                ('import_shipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_import_purchases_package', to='major_features.importshipment')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_involving_import_purchases', to='major_features.product')),
            ],
        ),
        migrations.CreateModel(
            name='ExportShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_shipment_value', models.IntegerField(blank=True, default=0, null=True)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_received_export_shipments', to='major_features.agency')),
                ('warehouse_management_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_following_export_shipments', to='major_features.warehousemanagementmethod')),
            ],
        ),
        migrations.CreateModel(
            name='ExportOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_take', models.IntegerField(default=0)),
                ('export_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_involving_import_purchases', to='major_features.exportorder')),
                ('import_purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_involving_export_orders', to='major_features.importpurchase')),
            ],
        ),
        migrations.AddField(
            model_name='exportorder',
            name='export_shipment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_export_orders_package', to='major_features.exportshipment'),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_involving_export_orders', to='major_features.product'),
        ),
    ]
