# Generated by Django 4.2 on 2023-04-20 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0003_exportorder_importpurchase_exportshipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccoutingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField()),
                ('date_end', models.DateField()),
                ('warehouse_management_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_applied_in_periods', to='major_features.warehousemanagementmethod')),
            ],
        ),
    ]
