# Generated by Django 4.2 on 2023-04-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0004_accoutingperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousemanagementmethod',
            name='is_currently_applied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
