# Generated by Django 4.2 on 2023-05-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0005_warehousemanagementmethod_is_currently_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportshipment',
            name='export_shipment_code',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='importshipment',
            name='import_shipment_code',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
