# Generated by Django 4.2 on 2023-05-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0006_exportshipment_export_shipment_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
