# Generated by Django 4.2 on 2023-05-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0007_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='address',
            field=models.TextField(blank=True, default='', max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, default='', max_length=1500, null=True),
        ),
    ]
