# Generated by Django 4.2 on 2023-06-24 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0008_agency_address_supplier_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='importshipment',
            name='warehouse_management_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_following_import_shipments', to='major_features.warehousemanagementmethod'),
        ),
    ]
