# Generated by Django 4.2 on 2023-06-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0009_importshipment_warehouse_management_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportshipment',
            name='warehouse_management_method',
        ),
        migrations.RemoveField(
            model_name='importshipment',
            name='warehouse_management_method',
        ),
    ]
