# Generated by Django 4.2 on 2023-06-24 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0010_remove_exportshipment_warehouse_management_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportshipment',
            name='current_accounting_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_following_export_shipments', to='major_features.accoutingperiod'),
        ),
        migrations.AddField(
            model_name='importshipment',
            name='current_accounting_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_following_import_shipments', to='major_features.accoutingperiod'),
        ),
    ]
