# Generated by Django 4.2.4 on 2023-09-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0011_exportshipment_current_accounting_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accoutingperiod',
            name='ending_inventory',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='accoutingperiod',
            name='starting_inventory',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
