# Generated by Django 4.2.4 on 2023-09-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0012_accoutingperiod_ending_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accoutingperiod',
            name='cogs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='accoutingperiod',
            name='quantity_inventory',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
