# Generated by Django 4.2.4 on 2023-09-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0014_remove_accoutingperiod_quantity_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='accoutingperiod',
            name='ending_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='accoutingperiod',
            name='starting_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
