# Generated by Django 4.2.4 on 2023-09-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0015_accoutingperiod_ending_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accoutingperiod',
            name='cogs',
        ),
        migrations.RemoveField(
            model_name='accoutingperiod',
            name='ending_inventory',
        ),
        migrations.RemoveField(
            model_name='accoutingperiod',
            name='ending_quantity',
        ),
        migrations.RemoveField(
            model_name='accoutingperiod',
            name='starting_inventory',
        ),
        migrations.RemoveField(
            model_name='accoutingperiod',
            name='starting_quantity',
        ),
    ]
