# Generated by Django 4.2.4 on 2023-09-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0016_remove_accoutingperiod_cogs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importpurchase',
            name='value_import',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
