# Generated by Django 4.2 on 2023-09-09 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0017_importpurchase_value_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_inventory', models.IntegerField(blank=True, default=0, null=True)),
                ('starting_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('total_cogs', models.IntegerField(blank=True, default=0, null=True)),
                ('ending_inventory', models.IntegerField(blank=True, default=0, null=True)),
                ('ending_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('accounting_period_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_period_inventory', to='major_features.accoutingperiod')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_product_inventory', to='major_features.product')),
            ],
        ),
    ]
