# Generated by Django 4.2 on 2023-09-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0019_accountingperiodinventory_import_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingperiodinventory',
            name='total_quantity_export',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
