# Generated by Django 4.2 on 2023-09-12 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0020_accountingperiodinventory_total_quantity_export'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportorder',
            name='total_order_value',
        ),
    ]
