# Generated by Django 4.2 on 2023-09-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0023_exportorderdetail_export_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='importshipment',
            name='total_shipment_remain',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
