# Generated by Django 4.2 on 2023-09-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0024_importshipment_total_shipment_remain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importshipment',
            name='total_shipment_remain',
        ),
    ]
