# Generated by Django 4.2 on 2023-10-23 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('major_features', '0025_remove_importshipment_total_shipment_remain'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportshipment',
            name='by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_export_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importshipment',
            name='by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_import_shipments', to=settings.AUTH_USER_MODEL),
        ),
    ]
