# Generated by Django 4.2 on 2023-11-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0026_exportshipment_by_admin_importshipment_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingperiodinventory',
            name='total_revenue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='exportshipment',
            name='shipment_revenue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
