# Generated by Django 4.2 on 2023-11-23 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0027_accountingperiodinventory_total_revenue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_total_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_on_hand',
        ),
    ]
