# Generated by Django 4.2 on 2023-11-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major_features', '0029_useractivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
